name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  job1:
    strategy:
      fail-fast: false
      matrix:
        include:
          - cmd: false
            continue-on-error: true
          - cmd: true
            continue-on-error: false
    runs-on: ubuntu-latest
    name: Test - ${{ matrix.cmd }}
    continue-on-error: "${{ matrix.continue-on-error }}"
    if: false
    steps:
      - run: ${{ matrix.cmd }}
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.job1.result }}
