name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    name: Test
    continue-on-error: true
    steps:
      - run: |
          exit 1
