name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ghc: ["8.6.5", "8.8.4", "8.10.2"]
    runs-on: ${{ matrix.os }}
    name: Test - v${{ matrix.ghc }} - ${{ matrix.os }}
    continue-on-error: "${{ matrix.ghc == '8.6.5' || matrix.ghc == '8.8.4' || matrix.ghc == '8.10.2' }}"
    steps:
      - run: |
          exit 1
