name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.10.3", "8.8.4", "8.6.5"]
    steps:
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: cabal v2-update && cabal list-bin cabal-plan
